
#-----------------------------------------------------------------------------#
# Application Properties #
# inside ./src/main/resources/application.yml
#-----------------------------------------------------------------------------#
# Turn on debug logging to show ConditionEvaluationReport :
debug: false

# Tomcat Server Port:
server:
  port: 8888

#-----------------------------------------------------------------------------#
